### ISSUE TITLE
Add complex tests on a simulated network

### ISSUE THREAD

**Issue by vkomenda** [Fantom-foundation/libconsensus-lachesis-rs#8]
There have to be more complex tests compared to the unit tests inside the modules. Such tests should perform message exchanges on a simulated network **which can include simulated Byzantine nodes** and check assertions about the state of the protocol as the message exchange progresses. Most properties from Opera/Fantom/Lachesis papers should be verifiable, for example:

* The correct nodes' DAGs are ordered topologically.
* All Clotho and Atropos events satisfy their theoretic creation conditions.
* The protocol terminates on finite input.

There are a couple of options for implementing complex tests: in the `tests` directory or in a subcrate. The former would probably be a better way to start.

A necessary requirement is the determinism of tests, see [`proptest`](https://crates.io/crates/proptest), which is helpful in tracing bugs found by randomised testing. For tests to be deterministic and repeatable, absolutely no non-deterministic IO should be performed. That is, the simulated network should deliver messages from a protocol instance to another protocol instance bypassing any system networking or message-passing layers.

**Comment by Maxime2** [comment]
Lachesis protocol has severe flaws in the design preventing it working correctly on scale. There is no point to put efforts to improve this repo further. Future development is in https://github.com/Fantom-foundation/libconsensus-dag and https://github.com/Fantom-foundation/libconsensus-raft-rs
